// Autogenerated by Mustache.
// Don't change the generated file manually, only the template

import Foundation

/// User liked a post
struct PostLikedEvent {
    let name = "PostLiked"
    let postId: String

    var data: [String: String] {
        "postId": postId,
    }
}

/// User commented on a post
struct PostCommentedEvent {
    let name = "PostCommented"
    let postId: String
    let length: String

    var data: [String: String] {
        "postId": postId,
        "length": length,
    }
}

/// User bookmarked a post
struct PostBookmarkedEvent {
    let name = "PostBookmarked"
    let postId: String
    let collectionId: String

    var data: [String: String] {
        "postId": postId,
        "collectionId": collectionId,
    }
}

